name: PR Telegram Notifier

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Функция для экранирования MarkdownV2 спецсимволов
          # Исправлено: - в конце, {} экранируются отдельно
          escape_md2() {
            echo "$1" | sed -E 's/([_*\[\]\(\)~`>#+=|.!-])/\\\1/g' | sed 's/{/\\{/g; s/}/\\}/g'
          }

          # Переменные PR
          HEAD=$(escape_md2 "${{ github.event.pull_request.head.ref }}")
          BASE=$(escape_md2 "${{ github.event.pull_request.base.ref }}")
          TITLE=$(escape_md2 "${{ github.event.pull_request.title }}")
          ACTOR=$(escape_md2 "${{ github.actor }}")
          URL=$(escape_md2 "${{ github.event.pull_request.html_url }}")
          ACTION="${{ github.event.action }}"
          MERGED="${{ github.event.pull_request.merged }}"

          # Если переменная пустая, делаем false
          if [ -z "$MERGED" ]; then
            MERGED=false
          fi

          # Массив строк для сообщения
          MESSAGE_LINES=()

          if [ "$ACTION" = "opened" ]; then
            MESSAGE_LINES+=("📢 *Новый Pull Request!*")
            MESSAGE_LINES+=("👤 Автор: $ACTOR")
            MESSAGE_LINES+=("🔀 Из ветки: $HEAD")
            MESSAGE_LINES+=("➡️ В ветку: $BASE")
            MESSAGE_LINES+=("📝 Заголовок: $TITLE")
            MESSAGE_LINES+=("🔗 $URL")

          elif [ "$ACTION" = "closed" ] && [ "$MERGED" = "true" ]; then
            MESSAGE_LINES+=("✅ *Pull Request смержен!*")
            MESSAGE_LINES+=("👤 Автор: $ACTOR")
            MESSAGE_LINES+=("🔀 Из ветки: $HEAD")
            MESSAGE_LINES+=("➡️ В ветку: $BASE")
            MESSAGE_LINES+=("📝 Заголовок: $TITLE")
            MESSAGE_LINES+=("🔗 $URL")

            # Напоминание про git pull для ветки dev
            if [ "$BASE" = "dev" ]; then
              MESSAGE_LINES+=("")
              MESSAGE_LINES+=("⚠️ *ВАЖНО! Не забудьте выполнить:*")
              MESSAGE_LINES+=("\`git pull origin dev\`")
            fi
          else
            echo "No notification needed for this action"
            exit 0
          fi

          # Объединяем массив в многострочную строку
          MESSAGE=$(printf "%s\n" "${MESSAGE_LINES[@]}")

          # Отправка в Telegram
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="MarkdownV2" \
            -d text="$MESSAGE"
