name: PR Telegram Notifier

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Функция для экранирования MarkdownV2 спецсимволов
          escape_md2() {
            echo "$1" | sed -E 's/([_\*\[\]\(\)~`>#+\-=|{}.!])/\\\1/g'
          }

          # Экранируем все данные PR
          HEAD=$(escape_md2 "${{ github.event.pull_request.head.ref }}")
          BASE=$(escape_md2 "${{ github.event.pull_request.base.ref }}")
          TITLE=$(escape_md2 "${{ github.event.pull_request.title }}")
          ACTOR=$(escape_md2 "${{ github.actor }}")
          URL=$(escape_md2 "${{ github.event.pull_request.html_url }}")
          ACTION="${{ github.event.action }}"
          MERGED="${{ github.event.pull_request.merged }}"

          # Формируем сообщение в одну строку с переносами \n
          if [ "$ACTION" = "opened" ]; then
            MESSAGE="📢 *Новый Pull Request!*\n👤 Автор: $ACTOR\n🔀 Из ветки: $HEAD\n➡️ В ветку: $BASE\n📝 Заголовок: $TITLE\n🔗 $URL"

          elif [ "$ACTION" = "closed" ] && [ "$MERGED" = "true" ]; then
            MESSAGE="✅ *Pull Request смержен!*\n👤 Автор: $ACTOR\n🔀 Из ветки: $HEAD\n➡️ В ветку: $BASE\n📝 Заголовок: $TITLE\n🔗 $URL"

            # Напоминание про git pull для ветки dev
            if [ "$BASE" = "main" ]; then
              MESSAGE="$MESSAGE\n\n⚠️ *ВАЖНО! Не забудьте выполнить:*\n\`git pull origin dev\`"
            fi
          else
            exit 0
          fi

          # Экранируем всю строку перед отправкой
          MESSAGE_ESCAPED=$(escape_md2 "$MESSAGE")

          # Отправка сообщения в Telegram
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="MarkdownV2" \
            -d text="$MESSAGE_ESCAPED"
